server:
  port: 8001

spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 4
      channel-topic:
        short-link-stats: 'short_link:stats-stream'
        short-link-stats-group: 'short_link:stats-stream:only-group'
  mvc:
    view:
      prefix: /templates/
      suffix: .html
message-queue:
  select: mq # 消息队列的实现方式 redis / mq

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

short-link:
  domain:
    default: nurl.ink:8001
  goto-domain:
    white-list:
      enable: true
      names: '拿个offer,知乎,掘金,博客园'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com

  stats:
    locale:
      amap-key: 1e0b68eae2562f29713adbaa46ec10ad

rocketmq:
  name-server: 192.168.127.100:9876 # 访问地址   http://common-rocketmq-dev.magestack.cn:8088/  192.168.127.100
  producer:
    group: short-link_project-service_stats-save_pg_rwz # 必须指定group
    topic: short-link_project-service_topic_rwz
    send-message-timeout: 2000 # 消息发送超时时长，默认3s
    retry-times-when-send-failed: 1 # 同步发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 1 # 异步发送消息失败重试次数，默认2
  consumer:
    group: short-link_project-service_stats-save_cg_rwz